import Head from 'next/head'
import { useContext } from 'react'
// import Image from 'next/image'
import Feeds from '../compnents/Feeds'
import { AuthContext } from '../context/auth'
import { useRouter } from 'next/router';


export default function Home() {
const {user}=useContext(AuthContext);


const Redirect=()=>{
  const router=useRouter();
  router.push("/login");
  return null;
}

  return (
    <div >
      <Head>
        <title>Reels-Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    {
      user?.uid? <Feeds/>:<Redirect/>

    }
     
    </div>
  )
}
